import '@fontsource/ubuntu/latin-300.css';
import '@fontsource/ubuntu/latin-400.css';
import '@fontsource/ubuntu/latin-500.css';
import '@fontsource/ubuntu/latin-700.css';
import React from 'react';
import ReactDOM from 'react-dom/client';
import { App } from './app/App';
import { Providers } from './app/Providers';
import './shared/styles/index.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><Providers><App /></Providers></React.StrictMode>);
